### ISSUE TITLE
buku tidak dapat render pada local host

### ISSUE THREAD

**Issue by Joosee24** [pplg-smk-metland/metschoo-library#45]
## Describe the bug
pada local host buku tidak dapat render ketika kita pindah tab / halaman , 
sehingga buku dapat muncul dengan reload

**Comment by Klrfl** [comment]
Pada saat pengembangan sepertinya yang terpengaruh itu semua halaman. Untuk sementara workaround-nya tinggal di-refresh saja.

**Comment by Klrfl** [comment]
Saat navigasi dan berhenti sebentar selama beberapa detik, sepertinya pada fungsi lifecycle hook `onMounted` pada sebagian besar halaman, kode berhenti di fungsi async. Karena berhenti itulah kode tidak sampai pada `isLoading.value = false` jadi indikator loading terus ditampilkan. Masih belum tau sejauh ini penyebabnya apa
