### ISSUE TITLE
sign up tidak mendapatkan confirm 

### ISSUE THREAD

**Issue by Joosee24** [pplg-smk-metland/metschoo-library#46]
## Describe the bug
sign up tidak mendapatkan konfirmasi pada gmail .

**Comment by Klrfl** [comment]
Akan dibuat email khusus sebentar lagi, jadi semoga bisa membuat fitur konfirmasi segera setelahnya

**Comment by Klrfl** [comment]
Oke Metschoo Library sudah mendapatkan email sendiri, SMTP juga sudah disetup, tinggal testing

bug yang gua temukan
-  username masih default value dari database, yang dimasukkan pengguna tidak dihiraukan (aaa)
