### ISSUE TITLE
Tambahkan no. HP

### ISSUE THREAD

**Issue by Klrfl** [pplg-smk-metland/metschoo-library#49]
tambahkan info nomor handphone (no. HP) pengguna. Bersama dengan email, admin menggunakan no. HP untuk menghubungi peminjam bilamana buku telat atau tidak dikembalikan.

- [x] tambah input baru untuk memasukkan no. HP di form signup
- [ ] tambahkan link wa.me yang mengarah ke no. WA pengguna 
- ~[ ] tambahkan provider verifikasi no. HP di Supabase~
- ~[ ] implementasi verifikasi no. HP~

**Comment by Klrfl** [comment]
Sepertinya verifikasi tidak akan bisa diimplementasi karena providernya berbayar semua..

**Comment by Adreon19** [comment]
aku nak buat juga😹
